CREATE TABLE flo_heatlh_hackathon.team7.np_meal_ingredients (
  meal_id STRING COLLATE UTF8_BINARY,
  food_name STRING COLLATE UTF8_BINARY,
  grams DOUBLE,
  ingredient_role STRING COLLATE UTF8_BINARY,
  is_primary BOOLEAN)
USING delta
COMMENT 'Step 2 / Gap C. Synthetic ingredient lists linking each of the 500 cycle_meal_plans meals to real foods in team7.np_nutrition_enriched. Generated by keyword/alias matching on meal_name with cycle diet-tag compliance (vegan/vegetarian/pescatarian/dairy_free/gluten_free). grams per 100g-basis food. Every food_name exists in np_nutrition_enriched; every meal has >=3 ingredients.'
TBLPROPERTIES (
  'delta.checkpoint.writeStatsAsJson' = 'false',
  'delta.checkpoint.writeStatsAsStruct' = 'true',
  'delta.enableDeletionVectors' = 'true',
  'delta.enableRowTracking' = 'true',
  'delta.feature.appendOnly' = 'supported',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.domainMetadata' = 'supported',
  'delta.feature.invariants' = 'supported',
  'delta.feature.rowTracking' = 'supported',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7',
  'delta.parquet.compression.codec' = 'zstd')
